; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Miro17\source\repos\M-i-r-o-17\PracticalTask\x64\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
